theme = "dhruv-archives-theme"
baseURL = "http://example.org/"
languageCode = "en-us"
title = "Theme Font Test"

[params]
  google_fonts = [
    ["Jersey 15", "400"],
    ["Jersey 25 Charted", "400"],

    ["Tomorrow", "400,700"],
    ["Roboto", "400,700"]
  ]
